# constants for drawing views
MENU_BAR_HEIGHT_RATIO    = 0.12
MENU_BAR_WIDTH_RATIO     = 1
TARGET_GRID_HEIGHT_RATIO = 1 - MENU_BAR_HEIGHT_RATIO
TARGET_GRID_WIDTH_RATIO  = 0.5
GAME_GRID_HEIGHT_RATIO   = 1 - MENU_BAR_HEIGHT_RATIO
GAME_GRID_WIDTH_RATIO    = 0.5
